### ISSUE TITLE
Right segments not rendering

### ISSUE THREAD

**Issue by FunnyGhost** [joshwcomeau/react-retro-hit-counter#6]
I'm having an issue where the right segments are not rendering. I'm definitely doing something wrong
<img width="180" alt="CleanShot 2022-02-22 at 23 34 23@2x" src="https://user-images.githubusercontent.com/6450559/155231195-64d5c967-1dad-4293-a9a7-1f33c4942eea.png">
.

You can see it in action here: https://catalincodes.vercel.app/posts/test-driven-development-in-an-angular-world-part-1

I copy pasted the code form the setup and changed a few properties 🤔.
I also tried disabling all my global styles. Not sure what else to try.

**Comment by FunnyGhost** [comment]
I identified that if I remove this empty tag from the `head`, the issue is fixed 
<img width="501" alt="CleanShot 2022-02-23 at 08 51 06@2x" src="https://user-images.githubusercontent.com/6450559/155279566-b83bff28-6d8a-4fc9-b9e8-8c298de6bfda.png">

it's an empty tag, though.

**Comment by FunnyGhost** [comment]
Found the issue. It was this line in my GlobalStyles.

```css
/*
  6. Improve media defaults
*/
img, picture, video, canvas, svg {
  display: block;
  max-width: 100%;
}
```
